name: New DO VM
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
# Job name is Greeting
    build:
        name: Create VM
        # This job runs on Linux
        runs-on: ubuntu-latest
        steps:
        # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
        - name: Hello world
          uses: actions/checkout@v2
          run : echo "Creating new VM on Digital Ocean"
        - name: Script
          env : 
            DO_TOKEN: ${{ secrets.DO_TOKEN }}
          run : ./scripts/create_vm.sh
